# Generated by Django 4.2.5 on 2023-10-13 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_usermessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermessage',
            name='content',
            field=models.TextField(default='message placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactermessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation'),
        ),
        migrations.AddField(
            model_name='charactermessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charactermessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
